# Generated by Django 3.1.4 on 2021-01-07 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='items',
            name='description',
        ),
    ]
