# Generated by Django 3.1.4 on 2021-01-07 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0002_remove_items_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='Wakeup',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='items',
            name='afternoon',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='items',
            name='morning',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='items',
            name='nigth',
            field=models.TextField(blank=True, null=True),
        ),
    ]
