# Generated by Django 3.1.4 on 2021-01-09 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0003_auto_20210108_0013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='Wakeup',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='items',
            name='date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
