# Generated by Django 3.1.4 on 2021-01-12 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0005_auto_20210112_2034'),
    ]

    operations = [
        migrations.RenameField(
            model_name='items',
            old_name='Wakeup',
            new_name='time',
        ),
    ]
