# Generated by Django 3.1.4 on 2021-01-14 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0006_auto_20210112_2110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='category',
            field=models.CharField(blank=True, choices=[('WakeUp', 'WakeUp'), ('Studies', 'Studies'), ('My Work', 'My Work'), ('Entertainment', 'Entertainment'), ('Political_News', 'Political_News'), ('Bussiness_Decions', 'Bussiness_Decions')], max_length=400),
        ),
        migrations.AlterField(
            model_name='items',
            name='feedback',
            field=models.CharField(blank=True, choices=[('Good', 'Good'), ('Bad', 'Bad')], max_length=120),
        ),
    ]
