# Generated by Django 3.1.4 on 2021-01-25 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0007_auto_20210115_0035'),
    ]

    operations = [
        migrations.CreateModel(
            name='ToDoItems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('time', models.TimeField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('place', models.URLField(blank=True, null=True)),
                ('category', models.CharField(blank=True, choices=[('WakeUp', 'WakeUp'), ('Studies', 'Studies'), ('My Work', 'My Work'), ('Entertainment', 'Entertainment'), ('Political_News', 'Political_News'), ('Bussiness_Decions', 'Bussiness_Decions')], max_length=400)),
            ],
        ),
    ]
