# Generated by Django 3.1.4 on 2021-01-25 14:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('diary', '0009_auto_20210125_1745'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todoitems',
            name='category',
        ),
        migrations.RemoveField(
            model_name='todoitems',
            name='place',
        ),
        migrations.AlterField(
            model_name='items',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='todoitems',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
