# Generated by Django 3.1.4 on 2021-01-29 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smb', '0002_wiwarana_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='wiwarana',
            name='lesson',
            field=models.CharField(blank=True, choices=[('unit', 'unit'), ('mechanics ', 'mechanics'), ('waves', 'waves'), ('optics', 'optics'), ('heat', 'heat'), ('gravity', 'gravity'), ('electro', 'electro'), ('magnetic', 'magnetic'), ('current', 'current'), ('elctronics ', 'electronic'), ('propertise of matter', 'propertise of matter'), ('heat wave', 'heat wave')], max_length=500, null=True),
        ),
    ]
