# Generated by Django 3.1.4 on 2020-12-20 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web1', '0003_auto_20201220_1016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='category',
            field=models.CharField(blank=True, choices=[('Biscuts', 'Biscuts'), ('Vegetables', 'Vegetables'), ('Grocery', 'Grocery'), ('beauty', 'bauty'), ('fruits', 'fruits')], max_length=10, null=True),
        ),
    ]
