# Generated by Django 3.1.4 on 2020-12-24 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web1', '0006_auto_20201220_1947'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='note',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
