# Generated by Django 3.1.4 on 2021-01-06 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web1', '0007_order_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='category',
            field=models.CharField(blank=True, choices=[('SmartPhone', 'SmartPhone'), ('Laptop', 'Laptop'), ('Tv', 'Tv'), ('Hometheather', 'Hometheater'), ('Desktop', 'Desktop')], max_length=40, null=True),
        ),
    ]
