# Generated by Django 3.1.4 on 2021-01-22 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web1', '0012_products_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='qtn',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
